services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always #コンテナを自動的に開始
    container_name: postgresql16-bigm
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tests
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  db_data:
